"""Browser-engine seam for the supervised workspace live-view protocol."""
from __future__ import annotations

import ctypes
import json
import logging
import os
import select
import signal
import subprocess
import time
from abc import ABC, abstractmethod
from importlib.util import find_spec
from pathlib import Path
from typing import Any, Callable
from urllib.parse import unquote, urlparse

log = logging.getLogger(__name__)

_PR_SET_PDEATHSIG = 1


def _playwright_proxy(proxy: str) -> dict[str, Any]:
    """Turn a proxy URL into the dict Playwright/Camoufox expect.

    Credentials ride in the URL userinfo (``http://user:pass@host:8080``);
    Playwright wants them split out, and a schemeless ``host:port`` is HTTP.
    """
    parsed = urlparse(proxy if "://" in proxy else f"http://{proxy}")
    server = f"{parsed.scheme}://{parsed.hostname or ''}"
    if parsed.port:
        server += f":{parsed.port}"
    result: dict[str, Any] = {"server": server}
    if parsed.username:
        result["username"] = unquote(parsed.username)
    if parsed.password:
        result["password"] = unquote(parsed.password)
    return result


class WorkspaceBrowserEngine(ABC):
    engine_id = "unknown"

    @property
    def capabilities(self) -> dict[str, Any]:
        return {"engine": self.engine_id, "supported": False, "display_capture": False}

    @abstractmethod
    def launch_options(
        self, *, profile: Path, fingerprint: Any, display: str = "",
        xauthority: str = "", proxy: str = "", dynamic_viewport: bool = False,
        audio_sink: str = "",
    ) -> dict[str, Any]: ...

    @abstractmethod
    def context_manager(self, launch_options: dict[str, Any]) -> Any: ...

    async def shutdown(self, context_manager: Any) -> None:
        await context_manager.__aexit__(None, None, None)

    async def create_page(self, context: Any) -> Any:
        return await context.new_page()

    async def metadata(self, page: Any) -> dict[str, str]:
        return {"url": str(getattr(page, "url", "") or ""), "title": str(await page.title() or "")}

    async def activate(self, page: Any) -> None:
        await page.bring_to_front()

    async def prepare_user_control(self, page: Any) -> None:
        await self.activate(page)

    async def release_user_control(self, page: Any) -> None:
        return None


class CamoufoxEngine(WorkspaceBrowserEngine):
    engine_id = "camoufox"

    @property
    def capabilities(self) -> dict[str, Any]:
        return {"engine": self.engine_id, "supported": True, "display_capture": True, "persistent_profile": True}

    def launch_options(
        self, *, profile: Path, fingerprint: Any, display: str = "",
        xauthority: str = "", proxy: str = "", dynamic_viewport: bool = False,
        audio_sink: str = "",
    ) -> dict[str, Any]:
        from camoufox.addons import DefaultAddons

        env = dict(os.environ)
        if display:
            env.update({"DISPLAY": display, "GDK_BACKEND": "x11", "MOZ_ENABLE_WAYLAND": "0"})
            if xauthority:
                env["XAUTHORITY"] = xauthority
            env.pop("WAYLAND_DISPLAY", None)
            if audio_sink:
                # Route every browser audio stream into the private null sink
                # the live view captures. The machine's speakers never play it.
                env["PULSE_SINK"] = audio_sink
        else:
            # Camoufox virtual Xvfb must own DISPLAY. A leaked :N from a previous
            # virtual launch, or the host Wayland session, makes Firefox wait on
            # a socket that will never accept this profile.
            env.pop("WAYLAND_DISPLAY", None)
            env.pop("DISPLAY", None)
        options = {
            "headless": False if display or os.name == "nt" else "virtual",
            "virtual_display": display or None,
            "env": env,
            # Camoufox 0.4.11 checks ``isinstance(humanize, (int, float))``
            # after accepting bool.  Since bool subclasses int in Python,
            # passing True serializes ``humanize:maxTime`` as a boolean even
            # though the browser requires a double and rejects it repeatedly.
            # Use the documented numeric form explicitly.
            "humanize": 1.5,
            "os": "windows",
            "persistent_context": True,
            "user_data_dir": str(profile),
            "fingerprint": fingerprint,
            # The profile fingerprint is intentionally generated by Camoufox,
            # persisted, versioned, and supplied again on every launch.
            "i_know_what_im_doing": True,
            "exclude_addons": list(DefaultAddons),
            "args": ["--kiosk"] if display else [],
            "firefox_user_prefs": {
                "browser.sessionstore.resume_from_crash": False,
                "browser.startup.page": 0,
                # Camoufox's privacy baseline sets this to zero, which makes
                # Playwright go_back/go_forward return successfully without
                # moving anywhere. The supervised toolbar promises ordinary
                # browser history, so retain a bounded stack. Its separate
                # max_total_viewers=0 default still prevents cached live pages
                # from accumulating in memory; entries reload when traversed.
                "browser.sessionhistory.max_entries": 50,
                "browser.link.open_newwindow": 3,
                "browser.link.open_newwindow.restriction": 0,
                "browser.link.open_newwindow.override.external": 3,
                # Remote control wants the page to move on the same frame the
                # wheel arrives. Firefox's smooth-scroll animation adds 100-200ms
                # of perceived lag to every remote scroll (the live view captures
                # the animated motion, not the final position), so disable it and
                # apply the smallest wheel step immediately.
                "general.smoothScroll": False,
                "general.smoothScroll.lines": False,
                "general.smoothScroll.mouseWheel": False,
                "general.smoothScroll.other": False,
                "general.smoothScroll.pages": False,
                "general.smoothScroll.scrollByPixel": False,
                "mousewheel.min_line_scroll_amount": 1,
                # Firefox's full-page Ctrl+plus/minus zoom follows the current
                # site, including other open tabs there, but not other sites.
                "browser.zoom.siteSpecific": True,
                # Xvfb has no vsync, so Firefox paints on its own 60 Hz timer
                # and a remote click waited ~2 ticks (31 ms p50) to reach the
                # screen. 120 Hz halves that (15 ms p50) and is a common real
                # display rate. Capture stays 60 fps.
                "layout.frame_rate": 120,
                # Firefox paints title-attribute tooltips in separate native X
                # windows. The selected-window capture sees only their opaque
                # backing rectangle, producing a black box in the live view.
                # Keep page overlays and the link URL status preview, but avoid
                # opening these uncapturable native tooltips during a session.
                "ui.tooltip.delay_ms": 86_400_000,
                # Throttle only runaway background timers. In the shared window
                # every tab except the selected one is "background" — including
                # tabs the agent is actively driving — so a flat timeout clamp
                # stalls agent flows that rely on timers, and low-memory tab
                # unload discards pages the manager treats as resident, fighting
                # its restorability bookkeeping. Suspending idle tabs on
                # live-view connect does the real resource reduction instead.
                "dom.timeout.enable_budget_timer_throttling": True,
            },
        }
        # Camoufox normally pins inner/outer window dimensions in CAMOU_CONFIG.
        # Playwright and the window manager can physically resize the window,
        # but those four overrides keep both page layout and JS-visible geometry
        # frozen. Build Camoufox's ordinary validated options first, then omit
        # only those dimensions at the final config boundary. Screen, DPR, UA,
        # fonts and the rest of the per-profile identity remain unchanged.
        # This is restricted to our supervised display; Camoufox's own virtual
        # display does not expose a resize/capture transaction.
        if dynamic_viewport and display:
            options["_odysseus_flexible_window"] = True
        if proxy:
            options["proxy"] = _playwright_proxy(proxy)
            # Locale, timezone, geolocation and the WebRTC IP must agree with
            # the proxy exit or a proxied browser contradicts itself on the
            # first check. Camoufox's geoip resolves the exit IP *through this
            # proxy* and fills exactly those keys — the pinned fingerprint sets
            # none of them, so there is no conflict with the stable identity.
            if find_spec("geoip2") is not None:
                options["geoip"] = True
            else:
                log.warning(
                    "browser_work_proxy is set but camoufox[geoip] is not installed; "
                    "locale/timezone will not follow the proxy exit",
                )
        return options

    def context_manager(self, launch_options: dict[str, Any]) -> Any:
        from camoufox.async_api import AsyncCamoufox

        _driver_env_with_compile_cache()
        options = dict(launch_options)
        if options.get("headless") == "virtual":
            return _VirtualDisplayContext(options)
        flexible = bool(options.pop("_odysseus_flexible_window", False))
        if not flexible:
            return AsyncCamoufox(**options)

        # AsyncCamoufox exposes `from_options` specifically for callers that
        # need to inspect the generated Playwright launch configuration. Doing
        # this here keeps the compatibility workaround inside the engine seam
        # instead of modifying Camoufox's installed package or page JavaScript.
        from camoufox.utils import get_env_vars, get_target_os, launch_options as build_options

        persistent = bool(options.pop("persistent_context", False))
        prepared = build_options(**options)
        env = dict(prepared.get("env") or {})
        config_keys = sorted(
            (key for key in env if key.startswith("CAMOU_CONFIG_")),
            key=lambda key: int(key.rsplit("_", 1)[1]),
        )
        if not config_keys:
            raise RuntimeError("Camoufox did not produce a window fingerprint configuration")
        config = json.loads("".join(str(env[key]) for key in config_keys))
        for key in (
            "window.innerWidth", "window.innerHeight",
            "window.outerWidth", "window.outerHeight",
        ):
            config.pop(key, None)
        for key in config_keys:
            env.pop(key, None)
        # Preserve Camoufox's generated FONTCONFIG_FILE when possible. The
        # helper may generate the same mapping again, but its result also owns
        # correct chunk sizing for the platform.
        config_env = get_env_vars(config, get_target_os(config))
        if env.get("FONTCONFIG_FILE"):
            config_env["FONTCONFIG_FILE"] = env["FONTCONFIG_FILE"]
        env.update(config_env)
        prepared["env"] = env
        # Persistent Playwright contexts otherwise install a synthetic
        # 1280x720 viewport even in a headed browser. That viewport masks the
        # native X11 resize we just enabled: capture changes, while page layout
        # and inner/outer dimensions remain frozen. In flexible mode the real
        # Firefox window is the viewport owner.
        prepared["no_viewport"] = True
        _allow_phone_width_window(prepared.get("executable_path"))
        return AsyncCamoufox(from_options=prepared, persistent_context=persistent)


# Firefox's browser chrome sets ``:root { min-width: var(--window-min-width) }``
# (500px in Firefox 152, 450px before). The native X11 window still shrinks
# below that, but the page keeps laying out at the chrome minimum, so a 390px
# phone request read back as 450/500px and ``browser_viewport`` reported
# ``clamped``. Camoufox loads chrome overrides only from ``chrome.css`` beside
# its executable (the profile's userChrome.css is ignored), so the override has
# to live there. The backend still owns the real floor
# (``browser_liveview_min_viewport_width``).
# Firefox 135 (Camoufox's build) sets the minimum as a plain 450px, not through
# the variable, so the variable alone left phone requests clamped; the direct
# rule covers both. A new marker re-applies it to installs patched before.
_PHONE_WIDTH_MARKER = "/* odysseus: allow phone-width windows v2 */"
_PHONE_WIDTH_CSS = (
    f"\n{_PHONE_WIDTH_MARKER}\n"
    ":root { --window-min-width: 0px !important; }\n"
    ":root, #main-window { min-width: 0 !important; }\n"
)


def _allow_phone_width_window(executable_path: Any) -> None:
    """Idempotently lift Firefox's chrome minimum width in Camoufox's chrome.css."""
    if not executable_path:
        return
    chrome_css = Path(str(executable_path)).parent / "chrome.css"
    if not chrome_css.is_file():
        return
    try:
        current = chrome_css.read_text(encoding="utf-8")
        if _PHONE_WIDTH_MARKER in current:
            return
        with chrome_css.open("a", encoding="utf-8") as handle:
            handle.write(_PHONE_WIDTH_CSS)
    except OSError:
        # A read-only or relocated install still launches; narrow viewport
        # requests then read back clamped, which the tool reports truthfully.
        log.warning(
            "Could not lift the browser window minimum width in %s; phone-width "
            "viewports will be clamped", chrome_css, exc_info=True,
        )


def _die_with_parent() -> Callable[[], None]:
    """Return a preexec hook that SIGKILLs the child when this process dies.

    libc is resolved here, before the fork, so the child only makes the call.
    """
    prctl = ctypes.CDLL(None, use_errno=True).prctl
    return lambda: prctl(_PR_SET_PDEATHSIG, signal.SIGKILL)


def _start_virtual_display() -> tuple[subprocess.Popen, str]:
    """Start Camoufox's fallback Xvfb with the same arguments Camoufox uses."""
    from camoufox.virtdisplay import VirtualDisplay

    # Camoufox 0.5 made xvfb_args an instance property (it now depends on the
    # screen and compositing settings); read both from an instance so the
    # class attribute of older releases and the property of newer ones work.
    virtual = VirtualDisplay(debug=False)
    read_fd, write_fd = os.pipe()
    try:
        process = subprocess.Popen(  # nosec - fixed argv, no shell
            [virtual.xvfb_path, "-displayfd", str(write_fd), *virtual.xvfb_args],
            stdin=subprocess.DEVNULL, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
            start_new_session=True, pass_fds=(write_fd,), preexec_fn=_die_with_parent(),
            env={**os.environ, "__GLX_VENDOR_LIBRARY_NAME": "mesa", "LIBGL_ALWAYS_SOFTWARE": "1"},
        )
    except BaseException:
        os.close(read_fd)
        raise
    finally:
        os.close(write_fd)
    try:
        reported = b""
        deadline = time.monotonic() + 10
        while b"\n" not in reported:
            remaining = deadline - time.monotonic()
            if remaining <= 0 or not select.select([read_fd], [], [], remaining)[0]:
                raise RuntimeError("Xvfb did not report a display number")
            chunk = os.read(read_fd, 64)
            if not chunk:
                raise RuntimeError(f"Xvfb exited before reporting a display (exit={process.poll()})")
            reported += chunk
        return process, f":{int(reported.strip())}"
    except BaseException:
        process.kill()
        process.wait()
        raise
    finally:
        os.close(read_fd)


def _driver_env_with_compile_cache() -> None:
    """Give the Playwright driver Node's on-disk compile cache, and only it.

    Node re-parses and compiles the driver's JavaScript on every start. With
    NODE_COMPILE_CACHE it reuses V8 code from disk (keyed by file content and
    Node version, so never stale): ~0.25 s -> ~0.2 s per launch for ~3 MB of
    disk. Scoped to the driver: exporting it from this process would reach
    every Node child, including agent terminals.
    """
    try:
        from playwright._impl import _transport
        from ascended_browser.runtime.constants import DATA_DIR
    except Exception:
        return
    original = getattr(_transport, "get_driver_env", None)
    if original is None or getattr(original, "_odysseus_compile_cache", False):
        return
    cache_dir = str(Path(DATA_DIR) / "cache" / "node-compile-cache")

    def driver_env() -> dict:
        env = original()
        env.setdefault("NODE_COMPILE_CACHE", cache_dir)
        return env

    driver_env._odysseus_compile_cache = True  # type: ignore[attr-defined]
    _transport.get_driver_env = driver_env


class _VirtualDisplayContext:
    """AsyncCamoufox on a fallback Xvfb that this engine owns and always reaps.

    Camoufox's own ``headless="virtual"`` server runs in its own session and
    is killed only from a patched ``browser.close()``. A launch that timed out
    (``wait_for`` cancels Camoufox after it started Xvfb, dropping the handle),
    a failed launch, a crashed browser and a hard-killed app each stranded one
    idle server; one host collected ~165. This one dies on any failed enter,
    on exit, and with the app process itself.
    """

    def __init__(self, launch_options: dict[str, Any]) -> None:
        self.launch_options = launch_options
        self._inner: Any = None
        self._xvfb: subprocess.Popen | None = None

    async def __aenter__(self) -> Any:
        from camoufox.async_api import AsyncCamoufox

        self._xvfb, display = _start_virtual_display()
        try:
            self._inner = AsyncCamoufox(**{**self.launch_options, "headless": False, "virtual_display": display})
            return await self._inner.__aenter__()
        except BaseException:
            process = self._xvfb
            log.warning(
                "Camoufox launch on virtual display %s failed; its Xvfb (pid %s) %s",
                display, getattr(process, "pid", "?"),
                "is still running" if process is not None and process.poll() is None
                else f"had exited with {getattr(process, 'returncode', '?')}",
            )
            self._stop_xvfb()
            raise

    async def __aexit__(self, *exc_info: Any) -> Any:
        try:
            if self._inner is not None:
                return await self._inner.__aexit__(*exc_info)
        finally:
            self._stop_xvfb()

    def _stop_xvfb(self) -> None:
        process, self._xvfb = self._xvfb, None
        if process is not None and process.poll() is None:
            process.terminate()
            try:
                process.wait(timeout=2)
            except subprocess.TimeoutExpired:
                process.kill()
                process.wait()


class ChromiumEngine(WorkspaceBrowserEngine):
    engine_id = "chromium"

    @property
    def capabilities(self) -> dict[str, Any]:
        return {"engine": self.engine_id, "supported": False, "reason": "reserved for a future adapter"}

    def launch_options(
        self, *, profile: Path, fingerprint: Any, display: str = "",
        xauthority: str = "", proxy: str = "", dynamic_viewport: bool = False,
        audio_sink: str = "",
    ) -> dict[str, Any]:
        raise RuntimeError("Chromium supervised workspaces are not implemented")

    def context_manager(self, launch_options: dict[str, Any]) -> Any:
        raise RuntimeError("Chromium supervised workspaces are not implemented")


class ElectronEmbeddedEngine(WorkspaceBrowserEngine):
    """Chromium guests rendered inside the Ascended desktop app.

    Contract: docs/desktop/ARCHITECTURE.md § Embedded browser. The browser
    runs on the user's desktop; this engine reaches it through the loopback
    relay ``/api/desktop/cdp/<token>`` (routes/desktop_routes.py), which pipes
    CDP to the owner's connected desktop browser host. There is no local
    process, display, profile directory, fingerprint or proxy: the backend
    skips those steps when ``embedded`` is true.
    """

    engine_id = "electron-chromium"
    embedded = True
    presentation = "embedded"

    def __init__(self, owner: str) -> None:
        self.owner = owner or ""
        # id(page) -> (page, {"guest_key", "target_id"}); dropped on close.
        self._identities: dict[int, tuple[Any, dict[str, str]]] = {}
        self._identify_tasks: set[Any] = set()

    @property
    def capabilities(self) -> dict[str, Any]:
        try:
            from ascended_browser.runtime.desktop import desktop_host_status

            supported = bool(desktop_host_status(self.owner).get("use_for_agent"))
        except Exception:
            supported = False
        return {
            "engine": self.engine_id,
            "presentation": self.presentation,
            "supported": supported,
            "display_capture": False,
            "persistent_profile": False,
        }

    def launch_options(
        self, *, profile: Path | None = None, fingerprint: Any = None, display: str = "",
        xauthority: str = "", proxy: str = "", dynamic_viewport: bool = False,
        audio_sink: str = "",
    ) -> dict[str, Any]:
        return {"owner": self.owner}

    def context_manager(self, launch_options: dict[str, Any]) -> Any:
        return _ElectronCdpContext(str(launch_options.get("owner", self.owner) or ""))

    async def prepare_user_control(self, page: Any) -> None:
        # The user sees and drives the guest directly; no window to raise.
        return None

    async def create_page(self, context: Any) -> Any:
        page = await context.new_page()
        await self.identify(page)
        return page

    def identity(self, page: Any) -> dict[str, str]:
        entry = self._identities.get(id(page))
        return dict(entry[1]) if entry is not None and entry[0] is page else {}

    async def identify(self, page: Any) -> dict[str, str]:
        """Read which desktop <webview> renders this page (gateway guestKey).

        The gateway answers Target.getTargetInfo on a page session itself and
        adds the shell's ``guestKey``. Failure leaves the page without an
        identity; the UI then falls back to URL matching.
        """
        existing = self.identity(page)
        if existing:
            return existing
        try:
            session = await page.context.new_cdp_session(page)
            try:
                info = (await session.send("Target.getTargetInfo")).get("targetInfo") or {}
            finally:
                try:
                    await session.detach()
                except Exception:
                    pass
        except Exception:
            log.debug("Could not identify desktop browser page", exc_info=True)
            return {}
        identity = {
            "guest_key": str(info.get("guestKey") or ""),
            "target_id": str(info.get("targetId") or ""),
        }
        key = id(page)
        self._identities[key] = (page, identity)
        try:
            page.once("close", lambda _page=None, key=key: self._identities.pop(key, None))
        except Exception:
            pass
        return dict(identity)

    def identify_soon(self, page: Any) -> None:
        import asyncio

        try:
            task = asyncio.get_running_loop().create_task(self.identify(page))
        except RuntimeError:
            return
        self._identify_tasks.add(task)
        task.add_done_callback(self._identify_tasks.discard)


class _ElectronCdpContext:
    """Async context manager yielding the desktop's default BrowserContext."""

    def __init__(self, owner: str) -> None:
        self.owner = owner
        self._playwright: Any = None
        self._browser: Any = None

    async def __aenter__(self) -> Any:
        # Imported lazily: the token API lives with the desktop routes and is
        # in-process only (never an env var a tool could inherit).
        from playwright.async_api import async_playwright
        from ascended_browser.runtime.desktop import DesktopBrowserUnavailable, mint_cdp_token

        endpoint = mint_cdp_token(self.owner)  # raises DesktopBrowserUnavailable
        _driver_env_with_compile_cache()
        self._playwright = await async_playwright().start()
        try:
            self._browser = await self._playwright.chromium.connect_over_cdp(endpoint, timeout=20_000)
            if not self._browser.contexts:
                raise DesktopBrowserUnavailable("The desktop browser exposed no browser context")
            return self._browser.contexts[0]
        except BaseException:
            await self._stop()
            raise

    async def __aexit__(self, *exc_info: Any) -> None:
        await self._stop()

    async def _stop(self) -> None:
        browser, self._browser = self._browser, None
        playwright, self._playwright = self._playwright, None
        if browser is not None:
            try:
                # For a CDP connection this closes the transport only; the
                # desktop then closes the guests that belonged to it.
                await browser.close()
            except Exception:
                pass
        if playwright is not None:
            try:
                await playwright.stop()
            except Exception:
                pass


def desktop_engine_for_owner(owner: str) -> ElectronEmbeddedEngine | None:
    """The embedded engine when this owner's desktop host offers it, else None."""
    try:
        from ascended_browser.runtime.desktop import desktop_host_status

        status = desktop_host_status(owner or "")
    except Exception:
        return None
    if status.get("use_for_agent"):
        return ElectronEmbeddedEngine(owner or "")
    return None


def desktop_host_absent_for(owner: str) -> float:
    try:
        from ascended_browser.runtime.desktop import desktop_host_absent_for as _absent

        return float(_absent(owner or ""))
    except Exception:
        return 0.0


def desktop_host_connected(owner: str) -> bool:
    try:
        from ascended_browser.runtime.desktop import desktop_host_status

        return bool(desktop_host_status(owner or "").get("connected"))
    except Exception:
        return False
